### PR TITLE
updates

### PR DESCRIPTION
**Pull request by KunjShah95**

### CODE REVIEW

**Comment by KunjShah95** [comment]
the code for integrating keras model in to ur system kidnly check it out and do look into it

**Review by ombhojane — COMMENTED** [review]
hey @KunjShah95 
the codes are supposed to be implemented in core explainableai codes and not in any external files. the aim is to user can use keras models with explaianableai package

**Comment by KunjShah95** [comment]
So what should I do now

**Comment by ombhojane** [comment]
have a look to #74 
he's integrating tensorflow models support in core explainableai package

**Pull request closed without merging**
