### PR TITLE
Issue #8

### PR DESCRIPTION
**Pull request by Prathmesh-rajurkar**
Your issue #8  , is been solved in this commit

### CODE REVIEW

**Comment by ombhojane** [comment]
image

I'm facing this issue while running, are facing the same?

I tried to fix as:
def generate_report(self, section: List, filename='xai_report.pdf'):

but gave following error - 
An error occurred while generating the report: XAIWrapper.generate_report() missing 1 required positional argument: 'section'

**Comment by Prathmesh-rajurkar** [comment]
Pls Check Now @ombhojane

**Comment by Prathmesh-rajurkar** [comment]
Okay , I will be making some chnages , pls look after it 
Is it okay if I could (y/n) options in terminal ???

**Comment by Prathmesh-rajurkar** [comment]
Made changes according to your wish pls check @ombhojane

**Comment by ombhojane** [comment]
Thanks @Prathmesh-rajurkar for contribution!

**Comment by ombhojane** [comment]
#8 has been resolved

**Comment by Prathmesh-rajurkar** [comment]
Thank You So Much @ombhojane for the opportunity

**Pull request merged**
