### PR TITLE
 Improve Console Output Readability

### PR DESCRIPTION
**Pull request by AnujSaha0111**
Improve console output readability with enhanced print formatting using colorama

### CODE REVIEW

**Comment by ombhojane** [comment]
improve_console_output.py is looking correct, please try to integrate it with core package so it'll reflect in the logs

**Comment by AnujSaha0111** [comment]
check for the updated one

**Comment by ombhojane** [comment]
Hey @AnujSaha0111 efforts appreciated

We're expecting something like this:
**Example:**
```python
from colorama import Fore, Style

# Before
print("Analyzing model...")

# After
print(f"{Fore.BLUE}Analyzing model...{Style.RESET_ALL}")
print(f"Accuracy: {accuracy:.3f}")
```

You may remove the newly added codes, and just enhance the existing logic codes

Please reach out for any doubts

**Comment by AnujSaha0111** [comment]
updated the file with Enhanced console output readability with colorama

**Comment by ombhojane** [comment]
Please don't create any new file!
Add the changes in current core package files only!

**Comment by AnujSaha0111** [comment]
made changes in core.py

**Review by ombhojane — CHANGES_REQUESTED** [review]
code is looking good!

Please remove 'self._analyze_models()' this line with as it was previously ie. 'self.model_comparison_results = self._compare_models()'

I'll merge it just do this minor fix

**Comment by AnujSaha0111** [comment]
updated the core.py as per asked

**Comment by AnujSaha0111** [comment]
Check for the core.py after the commit message of 'Final Update core.py'

**Comment by ombhojane** [comment]
This PR has been reolved at #21

**Pull request closed without merging**
