### PR TITLE
Updated module for handling large datsets

### PR DESCRIPTION
**Pull request by DarshAgrawal14**
Fixed Issue : #2 
I initially started with chunking approach divided the dataset into chunks but due creation of chunks the class was becoming complex and slow 
Therefore i used Dask.dataframes instead of pandas this increases memory efficiency and can handle any dataset without hindering with other functions

Darsh Agrawal , GSSoC 24 extd contributor

### CODE REVIEW

**Review by ombhojane — COMMENTED** [review]
give steps for testing

**Comment by DarshAgrawal14** [comment]
Actually i added this function in the original module , but since then significant changes have been made such as methods like .analyse which got inlcuded when i pulled origin before commiting , after changes were made to repo i think the module itself is not working , if you want can send you test.py to test my method , because currently the module itself is not working for me

**Comment by ombhojane** [comment]
yes @DarshAgrawal14, I can see merge conflicts. please do a git pull and have your code changes there

**Comment by DarshAgrawal14** [comment]
@ombhojane  i have resolved the issue , the PR is ready to merge

**Comment by DarshAgrawal14** [comment]
@ombhojane , If you require any changes please let me know..

**Review by ombhojane — APPROVED** [review]
thanks for contributing!

**Pull request merged**
