### PR TITLE
Implement Support for Regression Models #1

### PR DESCRIPTION
**Pull request by KunjShah95**

### CODE REVIEW

**Comment by ombhojane** [comment]
Hey @KunjShah95 
to make quality contribution, it supposed to be integrated with core codes, and not another new files.

**Comment by KunjShah95** [comment]
ok sharing u the code in few minutes

**Comment by KunjShah95** [comment]
kindly check now

**Review by KunjShah95 — COMMENTED** [review]
Kindly check

**Review by ombhojane — CHANGES_REQUESTED** [review]
Perfect, please have a menaingful name to this codefile like 'RegressionSupport.py' and save this in new 'examples' dir

**Review by ombhojane — CHANGES_REQUESTED** [review]
can you make it RegressionModelSupport.py please
also create a examples dir, and save there

**Review by ombhojane — APPROVED** [review]
Perfect!
Thanks for contributing!!

**Comment by KunjShah95** [comment]
will i get one shout on any social media platform or any ahctober fest points or anything related to it

**Comment by ombhojane** [comment]
sure mension ur twitter handle

**Comment by KunjShah95** [comment]
@INDIA_KUNJ

**Pull request merged**
