### PR TITLE
Time Series Visualization

### LINKED ISSUE #16: Basic Time Series Visualization
Add simple time series plotting capabilities to help users visualize temporal data.

Approach

- Create basic time series plotting functions
- Add option to include time series plots in report
- Implement simple temporal feature importance

Testing

- Test with sample time series data
- Verify plot generation
- Check integration with existing report generation

### PR DESCRIPTION
**Pull request by sharayuanuse**
Fixes #16

### CODE REVIEW

**Review by ombhojane — APPROVED** [review]
Perfect!

**Comment by sharayuanuse** [comment]
I wanted to take a moment to express how much I enjoyed working on the time visualization task. It was a rewarding experience that allowed me to enhance my skills and contribute to the project.
If there are any additional tasks or projects where I could assist, I would love the opportunity to contribute further.

**Comment by ombhojane** [comment]
Hey @sharayuanuse 
even I really enjoyed going through your PR and implementation process!
You may raise another issue by enhancing #16 again with the implementation of explainableai package in it. I'll be happy to assist and any guidence!

**Comment by sharayuanuse** [comment]
Okay I will look more into this topic.

**Comment by sharayuanuse** [comment]
I have created issue #82 enhancing the above task with explainableai package. Please look into it.

**Pull request merged**
