### PR TITLE
Update the README file

### PR DESCRIPTION
**Pull request by alo7lika**
#84
The file has been updated by adding some pictures and enhancing it look to make it attractive and drive people to look for the projects

### CODE REVIEW

**Comment by alo7lika** [comment]
@ombhojane the task has been completed. You can review it. Thank you!

**Review by ombhojane — CHANGES_REQUESTED** [review]
This looks really cool!

the model insights image is good, but it that's static right? please look for real time updating way for this, or any other platform works!

**Comment by alo7lika** [comment]
> This looks cool!
> 
> The model insights image is good, but it's static, right? Please look for a real-time updating way for this or any other platform work!

I have made some changes you can check it @ombhojane. Thank you!

**Review by ombhojane — CHANGES_REQUESTED** [review]
still the images you've mensioned are static, and not proof for validation.

so better is to remove images without base!

also, please have multimodal example usage, if you removed...

**Comment by alo7lika** [comment]
> still the images you've mensioned are static, and not proof for validation.
> 
> so better is to remove images without base!
> 
> also, please have multimodal example usage, if you removed...

Done @ombhojane

**Review by ombhojane — APPROVED** [review]
Perfect

**Comment by alo7lika** [comment]
> Perfect

assign labels here GSSOC Ext 24 and HACKTOBERFEST UNDER THE LEVEL

**Comment by alo7lika** [comment]
> > Perfect
> 
> assign labels here GSSOC Ext 24 and HACKTOBERFEST UNDER THE LEVEL

@ombhojane

**Comment by alo7lika** [comment]
@ombhojane add "GSSOC-EXT" label on the PR

**Pull request merged**
