### PR TITLE
Added clear and consise comments to explaianble.ipynb

### PR DESCRIPTION
**Pull request by shravya312**
image

### CODE REVIEW

**Comment by shravya312** [comment]
can u review @ombhojane

**Review by ombhojane — COMMENTED** [review]
can you comment the all cells codes, it's difficult to review ipynb files over here!

**Comment by shravya312** [comment]
Haa sure can u add label 2. I have added detailed, clear comments and made it beginner friendly
I will add all the code cell in the comment right away

**Review by ombhojane — APPROVED** [review]
Thanks for contributing

**Pull request merged**
