### PR TITLE
feat : Add batch processing to analyze method for memory-efficient large dataset handling #66

### PR DESCRIPTION
**Pull request by Prakhar29Sharma**
Feat : #66 
- Added `batch_size` parameter to `analyze()` to allow for batch processing of large datasets.
- Implemented `_process_in_batches()` helper method to handle batch processing with optional parallel execution using `multiprocessing`.
- Refactored model evaluation, SHAP value calculation, and cross-validation to operate in batches.
- Implemented `_aggregate_results()` for efficient result aggregation after batch processing.
- Updated logging to display batch processing progress for improved feedback.
- Ensured backward compatibility when `batch_size` is not provided.

### CODE REVIEW

**Review by ombhojane — CHANGES_REQUESTED** [review]
Hey @Prakhar29Sharma 

this is looking really good.

I encountered some errors, this fix worked for me:
    def _aggregate_results(self, results):
        aggregated_result = {}
        for result in results:
            if isinstance(result, dict):
                for key, value in result.items():
                    if key not in aggregated_result:
                        aggregated_result[key] = []
                    aggregated_result[key].append(value)
            else:
                logger.error("Expected result to be a dictionary, but got: {}".format(type(result)))
        return aggregated_result

Also one potential issue is there:
xai_report is not been generated. Please fix this

1. pleas update your codes and commit the requested changes, you're almost done, I'm looking to merge this useful PR

**Comment by Prakhar29Sharma** [comment]
> Hey @Prakhar29Sharma
> 
> this is looking really good.
> 
> I encountered some errors, this fix worked for me:
> 
> ```
>     def _aggregate_results(self, results):
>         aggregated_result = {}
>         for result in results:
>             if isinstance(result, dict):
>                 for key, value in result.items():
>                     if key not in aggregated_result:
>                         aggregated_result[key] = []
>                     aggregated_result[key].append(value)
>             else:
>                 logger.error("Expected result to be a dictionary, but got: {}".format(type(result)))
>         return aggregated_result
> ```
> 
> Also one potential issue is there: xai_report is not been generated. Please fix this
> 
> 1. pleas update your codes and commit the requested changes, you're almost done, I'm looking to merge this useful PR

Thanks for the feedback @ombhojane , I've fixed the code as per your request

**Review by ombhojane — CHANGES_REQUESTED** [review]
Hey @Prakhar29Sharma 
stil it didn't worked that time.

FOLLOWING changed worked for me, please go through:

```
    def analyze(self, batch_size=None, parallel=False):
        logger.debug("Analysing...")
        results = {}

        logger.info("Evaluating model performance...")
        if batch_size:
            results['model_performance'] = self._process_in_batches(self._evaluate_model_in_batches, batch_size, parallel)
        else:
            results['model_performance'] = evaluate_model(self.model, self.X, self.y, self.is_classifier)

        logger.info("Calculating feature importance...")
        self.feature_importance = self._calculate_feature_importance()
        results['feature_importance'] = self.feature_importance

        logger.info("Generating visualizations...")
        self._generate_visualizations(self.feature_importance)

        logger.info("Calculating SHAP values...")
        if batch_size:
            shap_values = self._process_in_batches(self._calculate_shap_in_batches, batch_size, parallel)
            results['shap_values'] = shap_values
        else:
            results['shap_values'] = calculate_shap_values(self.model, self.X, self.feature_names)

        logger.info("Performing cross-validation...")
        if batch_size:
            cv_results = self._process_in_batches(self._cross_validate_in_batches, batch_size, parallel)
            results['cv_scores'] = (np.mean(cv_results['mean_score']), np.mean(cv_results['std_score']))
        else:
            mean_score, std_score = cross_validate(self.model, self.X, self.y)
            results['cv_scores'] = (mean_score, std_score)

        logger.info("Model comparison results:")
        results['model_comparison'] = self.model_comparison_results

        self._print_results(results)

        logger.info("Generating LLM explanation...")
        results['llm_explanation'] = get_llm_explanation(self.gemini_model, results)

        self.results = results
        return results
    
    def _process_in_batches(self, batch_func, batch_size, parallel=False):
        results = []
        num_batches = (len(self.X) + batch_size - 1) // batch_size  # Calculate number of batches

        if parallel:
            from multiprocessing import Pool
            with Pool() as pool:
                batch_results = pool.starmap(
                    batch_func, 
                    [(self.X[i:i + batch_size], self.y[i:i + batch_size]) for i in range(0, len(self.X), batch_size)]
                )
            results.extend(batch_results)
        else:
            for i in range(0, len(self.X), batch_size):
                X_batch = self.X[i:i + batch_size]
                y_batch = self.y[i:i + batch_size]
                batch_result = batch_func(X_batch, y_batch)
                results.append(batch_result)

                # Log progress
                batch_num = i // batch_size + 1
                logger.info(f"Processing batch {batch_num}/{num_batches}")

        # Aggregate results after batch processing
        return self._aggregate_results(results)

    # private helper functions    
    def _evaluate_model_in_batches(self, X_batch, y_batch):
        return evaluate_model(self.model, X_batch, y_batch, self.is_classifier)

    def _calculate_shap_in_batches(self, X_batch, _):
        return calculate_shap_values(self.model, X_batch, self.feature_names)
    
    def _cross_validate_in_batches(self, X_batch, y_batch):
        mean_score, std_score = cross_validate(self.model, X_batch, y_batch)
        return {'mean_score': mean_score, 'std_score': std_score}

    def _aggregate_results(self, results):
        if isinstance(results[0], np.ndarray):  # Check if the result is a NumPy array (SHAP values)
            return np.mean(results, axis=0)  # Average SHAP values across batches
        
        aggregated_result = {}
        for result in results:
            if isinstance(result, dict):
                for key, value in result.items():
                    if key not in aggregated_result:
                        aggregated_result[key] = []
                    aggregated_result[key].append(value)
            else:
                logger.error(f"Unexpected result type: {type(result)}")
        
        # Aggregate the results
        for key in aggregated_result:
            if key == 'confusion_matrix':
                aggregated_result[key] = sum(aggregated_result[key])
            elif isinstance(aggregated_result[key][0], (int, float, np.float64)):
                aggregated_result[key] = np.mean(aggregated_result[key])
            elif key in ['roc_curve', 'precision_recall_curve']:
                # For these, we'll just take the first one as an example
                aggregated_result[key] = aggregated_result[key][0]
            else:
                aggregated_result[key] = aggregated_result[key][0]  # Just take the first value for non-numeric results
        
        return aggregated_result
```

please test this out,
it generates xai_report along batch processing.

**Comment by ombhojane** [comment]
hey @Prakhar29Sharma please update the codes, I'm looking to merge this PR

**Comment by Prakhar29Sharma** [comment]
I've made the changes as requested, please review. thanks!

**Review by ombhojane — APPROVED** [review]

**Pull request merged**
